######################################################################################################
# CLUSTER INSTALLATION
######################################################################################################

# Install simple K8s cluster if no MLOps is selected
- name: create simple Kubernetes cluster
  import_playbook: routines/create_k8s.yml
  when: (is_runtime | bool) and (not is_mlops | bool)

# Install K8s cluster with Picasso if MLOps is selected
- name: create Picasso cluster
  import_playbook: routines/create_picasso.yml
  when: (is_runtime | bool) and (is_mlops | bool)

# Update config files
- name: update configuration files
  import_playbook: refresh.yml
  when: is_runtime | bool

# Picasso registration for all tenants
- name: configure Picasso
  import_playbook: routines/configure_picasso.yml
  when: (is_runtime | bool) and (is_mlops | bool)

# Fix GPU Node pod creation issue
- name: configure gworkers
  import_playbook: routines/configure_gworkers.yml
  when: is_runtime | bool

# Configure sample tenant for K8s
- name: configure K8s tenant
  import_playbook: routines/configure_k8s.yml
  when: (is_runtime | bool) and (not is_mlops | bool)

######################################################################################################
# MLOPS INSTALLATION (setup spark & kubeflow addons)
######################################################################################################
- name: configure MLOps tenant
  import_playbook: routines/configure_mlops.yml
  when: (is_runtime | bool) and (is_mlops | bool)

###
# Configure external Data Fabric
###

- name: configure EDF
  import_playbook: routines/configure_edf.yml
  when: is_mapr | bool
  