 ###################################
# HPE Container Platform Deployment
#
# for feature improvements contact: dirk.derichsweiler@hpe.com
# 
# modified by Erdinc Kaya <kaya@hpe.com>

### Update SSH settings
- name: Add ssh configuration for the user
  import_playbook: routines/update_ssh_config.yml
  vars:
    op: add

######################################################################################################
# PREPARE HOSTS (updates, selinux etc that is common to all hosts)
######################################################################################################
- name: Prepare ECP Hosts
  import_playbook: routines/prepare_centos.yml

### Install AD
- name: Install AD server
  import_playbook: routines/install_ad.yml
  when: install_ad | bool

######################################################################################################
# INSTALL FALCO (for workers)
######################################################################################################
- name: Install falco
  import_playbook: routines/install_falco.yml
  when: is_runtime | bool

######################################################################################################
# PREPARE GPU HOSTS
######################################################################################################
- name: Prepare GPU Nodes
  import_playbook: routines/prepare_gworkers.yml
  when: is_runtime | bool

######################################################################################################
# INSTALL ECP (on controller)
######################################################################################################
- name: Install ECP
  import_playbook: routines/install_ecp.yml
  when: is_runtime | bool

######################################################################################################
# SETUP LOCAL CLIENT (update hpecp and kubectl configurations and autocomplete settings)
######################################################################################################
- name: Configure hosts for env
  import_playbook: routines/configure_settings.yml
  when: is_runtime | bool

######################################################################################################
# IMPORT HOSTS (bring workers into ECP)
######################################################################################################

### Configure docker proxy and airgap settings if provided
- name: add docker proxy to workers
  import_playbook: routines/add_dockerproxy.yml
  when: docker_proxy is defined

- name: add airgap to workers
  import_playbook: routines/add_airgap.yml
  when: docker_registry is defined and yum_repo is defined

- name: Import Hosts
  import_playbook: routines/import_hosts.yml
  when: is_runtime | bool

######################################################################################################
# INSTALL External Data Fabric
######################################################################################################
- name: Prepare EDF Hosts
  import_playbook: routines/prepare_ubuntu.yml
  when: is_mapr | bool

- name: Join EDF hosts to AD
  import_playbook: routines/ad_integration.yml
  when: is_mapr | bool

- name: Install Data Fabric
  import_playbook: routines/install_edf.yml
  when: is_mapr | bool
