 ###################################
# HPE Container Platform Deployment
#
# for feature improvements contact: dirk.derichsweiler@hpe.com
# 
# modified by Erdinc Kaya <kaya@hpe.com>

######################################################################################################
# PREPARE HOSTS (updates, selinux etc that is common to all hosts)
######################################################################################################
- name: Prepare ECP Hosts
  import_playbook: routines/prepare_centos.yml 
  # when: skip_preparation is not defined

### Install AD
- name: Install AD server
  import_playbook: routines/install_ad.yml 
######################################################################################################
# INSTALL FALCO (for workers)
######################################################################################################
- name: Install falco
  import_playbook: routines/install_falco.yml
  when: is_runtime | bool

######################################################################################################
# INSTALL ECP (on controller)
######################################################################################################
- name: Install ECP
  import_playbook: routines/install_ecp.yml
  when: is_runtime | bool

######################################################################################################
# SETUP LOCAL CLIENT (update hpecp and kubectl configurations and autocomplete settings)
######################################################################################################
- name: Configure hosts for env
  import_playbook: routines/configure_settings.yml
  when: is_runtime | bool

######################################################################################################
# PREPARE GPU HOSTS
######################################################################################################
- name: Import Hosts
  import_playbook: routines/prepare_gworkers.yml
  when: is_runtime | bool

######################################################################################################
# IMPORT HOSTS (bring workers into ECP)
######################################################################################################
- name: Import Hosts
  import_playbook: routines/import_hosts.yml
  when: is_runtime | bool

######################################################################################################
# INSTALL MAPR (only for External Data Fabric)
######################################################################################################
- name: Prepare MapR Hosts
  import_playbook: routines/prepare_centos_mapr.yml
  when: is_mapr | bool

- name: Install External MapR Hosts
  import_playbook: routines/create_mapr.yml
  when: is_mapr | bool

