- name: Install and configure AD authentication
  hosts: mapr
  gather_facts: yes
  vars_prompt:

  vars:
    ad_realm: "{{ ad_domain | default('SAMDOM.EXAMPLE.COM') | upper }}"

  tasks:
    - name: Install ad_auth required tools for RedHat/CentOS 8
      package: 
        name: realmd,sssd,oddjob,oddjob-mkhomedir,adcli,samba-common,samba-common-tools,krb5-workstation,authselect-compat
        state: present
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'
      become: yes

    - name: Install ad_auth required tools for RedHat/CentOS 7
      package: 
        name: sssd,realmd,oddjob,oddjob-mkhomedir,adcli,samba-common,samba-common-tools,krb5-workstation,openldap-clients,policycoreutils-python,python3-pip
        state: present 
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'
      become: yes

    - name: Install ad_auth required tools for Ubuntu 2004
      package:
        name: sssd,realmd,oddjob,oddjob-mkhomedir,adcli,samba-common,krb5-user,openldap-utils,policycoreutils-python-utils,python3-pip
        state: present 
      when: ansible_facts['os_family'] == 'Debian'
      become: yes

    - name: configure sssd
      copy: dest=/etc/sssd/sssd.conf content={{ sssd_file }} mode=0600
      become: yes
      vars:
        sssd_file: |-
          [domain/{{ ad_realm }}]
            debug_level = 3
            autofs_provider = ldap
            cache_credentials = True
            id_provider = ldap
            auth_provider = ldap
            chpass_provider = ldap
            access_provider = ldap
            ldap_uri = ldap://{{ ad_server | default(groups['ad_server'] | first) }}:389
            ldap_search_base = {{ ad_base_dn }}
            ldap_id_use_start_tls = False
            ldap_tls_cacertdir = /etc/openldap/cacerts
            ldap_tls_reqcert = never
            ldap_user_member_of = memberOf
            ldap_access_order = filter
            ldap_access_filter = (|(memberOf={{ ad_admin_group }})(memberOf={{ ad_member_group }}))
            ldap_id_mapping = False
            ldap_schema = ad
            ldap_user_gid_number = gidNumber
            ldap_group_gid_number = gidNumber
            ldap_user_object_class = posixAccount
            ldap_idmap_range_size = 200000
            ldap_user_gecos = gecos
            fallback_homedir = /home/%u
            ldap_user_home_directory = homeDirectory
            default_shell = /bin/bash
            ldap_group_object_class = posixGroup
            ldap_user_uid_number = uidNumber
            ldap_referrals = False
            ldap_idmap_range_max = 2000200000
            ldap_idmap_range_min = 200000
            ldap_group_name = cn
            ldap_user_name = cn
            ldap_default_bind_dn = {{ ad_bind_dn }}
            ldap_user_shell = loginShell
            ldap_default_authtok = {{ ad_bind_pwd }}
            ldap_user_fullname = cn

          [sssd]
            services = nss, pam, autofs
            domains = {{ ad_domain | lower }}

          [nss]

          homedir_substring = /home

          [pam]

          [sudo]

          [autofs]

          [ssh]

          [pac]

          [ifp]

          [session_recording]
      when: ansible_facts['os_family'] == 'Debian'

    - shell: pam-auth-update --enable mkhomedir
      become: yes
      when: ansible_facts['os_family'] == 'Debian'

    - name: ensure AD can be discovered from hosts (cloud providers dont resolve to self-installed AD)
      lineinfile:
        dest: /etc/hosts
        line: "{{ ad_server | default(groups['ad_server'] | first) }}     {{ ad_domain }}"
      become: yes
      when: install_ad | bool

    - shell: "realm list | grep -q {{ ad_domain }}"
      register: realm_joined
      ignore_errors: yes

    - shell: |
        authselect select sssd --force
        echo "sudoers:    files sss" >> /etc/nsswitch.conf
        echo "session optional pam_oddjob_mkhomedir.so skel=/etc/skel/ umask=0022" >> /etc/pam.d/system-auth
        update-crypto-policies --set DEFAULT:AD-SUPPORT
      become: yes
      when: realm_joined is failed and (ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8')

    - service: name=oddjobd state=restarted enabled=yes
      become: yes
      when: realm_joined is failed

    - service: name=sssd state=restarted enabled=yes
      become: yes
      when: realm_joined is failed

    - shell: "realm discover {{ ad_domain }}"
      become: yes
      when: realm_joined is failed and ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'
      retries: 12 # retry for 5 minutes
      delay: 30
      register: realm
      until: realm.rc == 0

    - shell: "echo {{ ad_bind_pwd }} | realm join {{ ad_domain }} ; realm permit -a"
      become: yes
      when: realm_joined is failed and ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'
