- name: Install and configure AD authentication
  hosts: mapr
  gather_facts: yes
  vars_prompt:

  vars:
    ad_realm: "{{ (ad_domain | default('SAMDOM.EXAMPLE.COM')).split('.') | first }}"

  tasks:
    - name: Install ad_auth required tools for RedHat/CentOS 8
      package: 
        name: realmd,sssd,oddjob,oddjob-mkhomedir,adcli,samba-common,samba-common-tools,krb5-workstation,authselect-compat
        state: present
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'
      become: yes

    - name: Install ad_auth required tools for RedHat/CentOS 7
      package: 
        name: sssd,realmd,oddjob,oddjob-mkhomedir,adcli,samba-common,samba-common-tools,krb5-workstation,openldap-clients,policycoreutils-python,python3-pip
        state: present 
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'
      become: yes

    - name: Install ad_auth required tools for Ubuntu 2004
      package:
        name: sssd,realmd,oddjob,oddjob-mkhomedir,adcli,samba-common,krb5-user,openldap-utils,policycoreutils-python-utils,python3-pip
        state: present 
      when: ansible_facts['os_family'] == 'Debian'
      become: yes

    - name: configure sssd
      copy: dest=/etc/sssd/sssd.conf content={{ sssd_file }} mode=0600
      become: yes
      vars:
        sssd_file: |-
          [domain/{{ ad_realm | lower }}]
            debug_level = 3
            autofs_provider = ldap
            cache_credentials = True
            id_provider = ldap
            auth_provider = ldap
            chpass_provider = ldap
            access_provider = ldap
            ldap_uri = ldap://{{ ad_server | default(groups['ad_server'] | first) }}:389
            ldap_search_base = {{ ad_base_dn }}
            ldap_id_use_start_tls = False
            ldap_tls_cacertdir = /etc/openldap/cacerts
            ldap_tls_reqcert = never
            ldap_user_member_of = memberOf
            ldap_access_order = filter
            ldap_access_filter = (|(memberOf={{ ad_admin_group }})(memberOf={{ ad_member_group }}))
            ldap_id_mapping = False
            ldap_schema = ad
            ldap_user_gid_number = gidNumber
            ldap_group_gid_number = gidNumber
            ldap_user_object_class = posixAccount
            ldap_idmap_range_size = 200000
            ldap_user_gecos = gecos
            fallback_homedir = /home/%u
            ldap_user_home_directory = homeDirectory
            default_shell = /bin/bash
            ldap_group_object_class = posixGroup
            ldap_user_uid_number = uidNumber
            ldap_referrals = False
            ldap_idmap_range_max = 2000200000
            ldap_idmap_range_min = 200000
            ldap_group_name = cn
            ldap_user_name = cn
            ldap_default_bind_dn = {{ ad_bind_dn }}
            ldap_user_shell = loginShell
            ldap_default_authtok = {{ ad_bind_pwd }}
            ldap_user_fullname = cn

          [sssd]
            services = nss, pam, autofs
            domains = {{ ad_realm | lower }}

          [nss]

          homedir_substring = /home

          [pam]

          [sudo]

          [autofs]

          [ssh]

          [pac]

          [ifp]

          [secrets]

          [session_recording]

    - shell: pam-auth-update --enable mkhomedir
      become: yes

    - service: name=oddjobd state=restarted enabled=yes
      become: yes

    - service: name=sssd state=restarted enabled=yes
      become: yes
