######################################################################################################
# DOCKER PROXY
######################################################################################################
- hosts: "{{ groups['controllers'] | first }}"
  gather_facts: false
  vars:
    docker_proxy_username: "{{ docker_proxy | urlsplit('username') | default('') }}"
    docker_proxy_password: "{{ docker_proxy | urlsplit('password') | default('') }}"
    docker_proxy_url: "{{ ( (docker_proxy | urlsplit('hostname'), docker_proxy | urlsplit('port')) | join(':'), (docker_proxy | urlsplit('path')) ) | join('') }}"
    airgap_json: |
      {
        "airgap_parameters": {
          "container_repo_url": "{{ docker_proxy_url }}",
          "container_repo_username": "{{ docker_proxy_username }}",
          "container_repo_password": "{{ docker_proxy_password }}",
          "is_secure_container_repo": {{ docker_proxy | urlsplit('scheme') == 'https' }},
          "container_repo_client_certificate": "",
          "baseurl": "{{ yum_repo | default('') }}",
          "repo_gpg_key": "",
          "rpm_gpg_key": "",
          "support_rpm_repo": true
        }
      }
  tasks:
  - name: airgap config
    copy:
      dest: ~/airgap.json
      content: "{{ airgap_json }}"
      force: yes

  - name: configure airgap
    shell: hpecp httpclient put /api/v2/config/global_proxy --json-file ~/airgap.json
