######################################################################################################
# DOCKER PROXY
######################################################################################################

- hosts: workers:gworkers
  gather_facts: no

  tasks:
  - name: ensure /etc/docker exist
    file:
      path: /etc/docker
      state: directory
    become: yes
    register: folder

  - name: get existing config.json
    slurp:
      src: /etc/docker/daemon.json
    register: imported_json
    ignore_errors: yes

  - name: configure private docker registry
    copy:
      dest: /etc/docker/daemon.json
      content: "{{ imported_json.content | b64decode if not imported_json.failed else {} | combine( registry_json ) | to_json }}"
    register: docker_conf
    become: yes
    vars:
      insecure_json: "\"insecure-registries\":[\"{{ docker_proxy | urlsplit('hostname') }}\"],"
      insecure_registry: "{{ insecure_json if (docker_proxy | urlsplit('scheme') == 'http') else '' }}"
      registry_json: |
        {
          {{ insecure_registry }} "registry-mirrors": ["{{ docker_proxy }}"]
        }

  - name: restart dockerd for proxy
    systemd:
      state: restarted
      enabled: yes
      name: docker
    when: docker_conf.changed
    become: yes
    ignore_errors: yes