- hosts: localhost
  tasks:
  - name: configure hpecp
    blockinfile:
      dest: ~/.hpecp.conf
      marker: ; {mark} ANSIBLE MANAGED PLATFORM BLOCK
      create: yes
      block: |
        [default]
        api_host = {{ gateway_pub_dns }}
        api_port = 8080
        use_ssl = True
        verify_ssl = False
        warn_ssl = False
        username = admin
        password = {{ admin_password }}

- hosts: controllers:workers:gworkers
  tasks:
  - name: shell completion
    lineinfile:
      dest: ~/.bashrc
      line: source <(kubectl completion bash)
    