### Start MapR installation on first DF node
- hosts: "{{ (groups['mapr'] | first) | default([]) }}"
  tasks:
  - name: get mapr installer
    get_url:
      url: https://package.mapr.hpe.com/releases/installer/mapr-setup.sh
      dest: /tmp/mapr-setup.sh
      mode: '0755'

  - name: setup mapr installer
    command: /tmp/mapr-setup.sh -y
    become: yes
    register: install
  
  - name: copy private key
    copy:
      src: "../../generated/controller.prv_key"
      dest: "~/controller.prv_key"
      mode: 0600

  - name: get hostnames
    shell: getent hosts "{{ item }}" | awk '{ print $2 }'
    with_items: "{{ groups['mapr'] }}"
    register: hostnames

  - name: get hostlist
    set_fact:
      mapr_hosts: "{{ hostnames.results | map(attribute='stdout') | list }}"

  - shell: "fdisk -l | grep '500 GiB' | cut -d' ' -f2 | tr -d ':'"
    register: disks
    become: yes 
  - set_fact: mapr_disks="{{ disks.stdout_lines }}"
  #### NOT WORKING !!!
  # - debug: msg="{{ ansible_devices }}"
  # - set_fact: 
  #     disks: "{{ ansible_devices.keys() | reject('match', '^loop(.*)$') | list }}"
  # - set_fact: 
  #     mapr_disks: "{{ ansible_devices[item] | json_query(jmesquery) }}"
  #   loop: "{{ disks }}"
  #   vars:
  #     jmesquery: "[?size=='500.00 GB']"

  - name: update stanza
    copy:
      dest: /tmp/mapr.stanza
      content: |-
        environment:
          mapr_core_version: 6.2.0
        config:
          hosts:
            - "{{ mapr_hosts[0] }}"
            - "{{ mapr_hosts[1] }}"
            - "{{ mapr_hosts[2] }}"
          ssh_id: {{ ansible_user_id }}
          ssh_key_file: "{{ ansible_user_dir }}/controller.prv_key"
          metrics_ui_admin_password: admin
          license_type: M5
          mep_version: 8.0.0
          disks:
            - "{{ mapr_disks[0] }}"
            - "{{ mapr_disks[1] }}"
          cluster_name: dfdemo.local
          services:
            mapr-hivemetastore:
              database:
                name: hive
                user: hive
                password: mapr

      force: yes

  # - name: configure mapr
  #   command: "echo 'y' | sudo /opt/mapr/installer/bin/mapr-installer-cli install -nv -t /tmp/mapr.stanza"
