### Kubernetes Cluster with 1 Master and 1 Worker, no DF
- hosts: localhost
  gather_facts: yes
  tasks:
  - shell: "hpecp k8sworker get /api/v2/worker/k8shost/ -o json"
    register: output
    ignore_errors: yes
  - set_fact:
      workers: "{{ output.stdout | from_json }}"
  - set_fact:
      worker_ids: "{{ workers | json_query(jmesquery) }}"
    vars:
      jmesquery: "_embedded.k8shosts[]._links.self.href"
  - set_fact:
      master_list: "{{ worker_ids[:1] | map('regex_replace', '$', ':master') | list }}"
  - set_fact:
      worker_list: "{{ worker_ids[-2:] | map('regex_replace', '$', ':worker') | list }}"
  - set_fact:
      k8shost_list: "{{ master_list + worker_list }}"

  - name: creating K8s cluster
    shell: |-
      hpecp k8scluster create \
      --name k8scluster \
      --k8s_version "{{ k8s_version }}" \
      --k8shosts-config "{{ k8shost_list | join(',') }}" \
      --addons "{{ addons_list }}" \
      --ext_id_svr_bind_pwd "{{ ad_bind_pwd }}" \
      --ext_id_svr_user_attribute "{{ ad_user_attribute | default('sAMAccountName') }}" \
      --ext_id_svr_bind_type "{{ ad_bind_type | default('search_bind') }}" \
      --ext_id_svr_bind_dn "{{ ad_bind_dn | default('cn=Administrator,CN=Users,DC=samdom,DC=example,DC=com') }}" \
      --ext_id_svr_host "{{ install_ad | bool | ternary(groups['ad_server'] | first, ad_server) }}" \
      --ext_id_svr_group_attribute "{{ ad_group_attribute | default('memberOf') }}" \
      --ext_id_svr_security_protocol "{{ ad_security_protocol | default('ldaps') }}" \
      --ext_id_svr_base_dn "{{ ad_base_dn | default('CN=Users,DC=samdom,DC=example,DC=com') }}" \
      --ext_id_svr_verify_peer false \
      --ext_id_svr_type "{{ ad_type | default('Active Directory') }}" \
      --ext_id_svr_port "{{ ad_port | default(636) | int }}" \
      --external-groups "{{ default_external_groups }}"
    ignore_errors: yes
    vars:
      addons_53: '[]'
      addons_54: '["spark-operator", "istio"]'
      addons_list: "{{ addons_53 if (is_stable | bool) else addons_54 }}"
      default_external_groups: '[''{{ ad_admin_group }}'',''{{ ad_member_group }}'']'

  - shell: "hpecp k8scluster list -o text | cut -d' ' -f1"
    register: cluster_id

  - name: wait for K8s cluster
    shell: "hpecp k8scluster wait-for-status ''[ready]'' --id {{ cluster_id.stdout }} --timeout-secs 3600"
