#######################################################################################################
# HPECP Installation
# created by Dirk Derichsweiler, do not hesitate to contact me. k8s@hpe.com
# modified by Erdinc Kaya
# Tested with HPECP 5.3
#######################################################################################################

- hosts: "{{ (groups['controllers'] | first) | default([]) }}"
  gather_facts: yes
  tasks:
  - name: configure hpecp
    blockinfile:
      dest: ~/.hpecp.conf
      create: yes
      block: |
        [default]
        api_host = {{ groups['controllers'] | first }}
        api_port = 8080
        use_ssl = True
        verify_ssl = False
        warn_ssl = False
        username = admin
        password = {{ admin_password }}

  - name: copy private key
    copy:
      src: "../../generated/controller.prv_key"
      dest: "/home/centos/controller.prv_key"
      owner: "centos"
      group: "centos"
      mode: 0600

  - name: check if ecp is installed
    stat:
      path: "/opt/bluedata"
    register: hpecp_installed

  - name: check ecp install file
    stat:
      path: "/home/centos/{{ install_file }}"
    register: installation_file

  - name: download ecp install file
    get_url:
      url: "{{ download_url }}"
      dest: "/home/centos/{{ install_file }}"
      mode: '0755'
    when: not installation_file.stat.exists

  - stat: path=/home/centos/cert.pem
    register: cert_file
  - name: copy certificate
    copy:
      src: "../../generated/{{ gateway_pub_dns }}/cert.pem"
      dest: "/home/centos/cert.pem"
      owner: "centos"
      group: "centos"
      mode: 0644
    when: not cert_file.stat.exists

  - name: copy certificate key
    copy:
      src: "../../generated/{{ gateway_pub_dns }}/key.pem"
      dest: "/home/centos/key.pem"
      owner: "centos"
      group: "centos"
      mode: 0600
    when: not cert_file.stat.exists

  - name: copy minica certificate
    copy:
      src: "../../generated/minica.pem"
      dest: "/home/centos/minica.pem"
      owner: "centos"
      group: "centos"
      mode: 0600
    when: not cert_file.stat.exists

  - name: copy minica certificate key
    copy:
      src: "../../generated/minica-key.pem"
      dest: "/home/centos/minica-key.pem"
      owner: "centos"
      group: "centos"
      mode: 0600
    when: not cert_file.stat.exists

  - name: install ecp
    shell: "/home/centos/{{ install_file }} --skipeula --default-password {{ admin_password }} --ssl-cert /home/centos/cert.pem --ssl-priv-key /home/centos/key.pem --ssl-ca-data=/home/centos/minica.pem"
    when: not hpecp_installed.stat.exists
    # become: yes

  - name: configure ecp
    shell: /opt/bluedata/common-install/scripts/start_install.py -c "{{ groups['controllers'] | first }}" -p "{{ admin_password }}" -t 60 -s docker -d hpecplocal --cin "{{ project_id | replace('.', '_' ) }}" -k no --no-local-tenant-storage --routable no
    when: not hpecp_installed.stat.exists

  - name: install python3
    package:
      name:
        - python3
        - python3-pip
        - expect
      state: latest
    become: yes

  - name: install hpecp client
    shell: pip3 install --user hpecp pexpect

  - name: system-wide hpecp
    file:
      src: "/home/centos/.local/bin/hpecp"
      dest: "/usr/local/bin/hpecp"
      owner: root
      group: root
      state: link
      mode: 0755
    become: yes

  - name: check ecp gateway
    shell: ~/.local/bin/hpecp gateway list --output text
    register: gw_result

  - name: site lockdown
    shell: ~/.local/bin/hpecp lock create "Install Gateway"
    when: gw_result.stdout == ""

  - name: install ecp gateway
    shell: ~/.local/bin/hpecp gateway create-with-ssh-key --ip "{{ item }}" --proxy-node-hostname "{{ gateway_pub_dns }}" --ssh-key-file ./controller.prv_key
    with_items: "{{ groups['gateway'] | list }}"
    when: gw_result.stdout == ""

  - name: exit site lockdown
    shell: ~/.local/bin/hpecp lock delete-all --timeout-secs 1800
    when: gw_result.stdout == ""

  - name: AD config
    copy:
      dest: ~/adconf.json
      content: |-
        {
          "external_identity_server":  {
            "host":"{{ ad_server | default(groups['ad_server']) | first | default([]) }}",
            "port": {{ ad_port | default('636') | int }},
            "bind_dn":"{{ bind_dn | default('cn=Administrator,CN=Users,DC=samdom,DC=example,DC=com') }}",
            "bind_pwd":"{{ bind_pwd }}",
            "user_attribute":"{{ user_attribute | default('sAMAccountName') }}",
            "group_attribute":"{{ group_attribute | default('member') }}",
            "bind_type":"{{ bind_type | default('search_bind') }}",
            "security_protocol":"{{ security_protocol | default('ldaps') }}",
            "base_dn":"{{ base_dn | default('CN=Users,DC=samdom,DC=example,DC=com') }}",
            "type":"{{ type | default('Active Directory') }}",
            "verify_peer": false
          }
        }
      force: yes

  - name: configure global AD
    shell: ~/.local/bin/hpecp httpclient post /api/v2/config/auth --json-file ~/adconf.json
    register: result
    retries: 5
    delay: 60
    until: result is not failed
