- hosts: ad_server
  # any_errors_fatal: yes
  gather_facts: yes

  tasks:
  - name: install docker
    package:
      name: 
        - docker
        - openldap-clients
      state: latest
    become: yes

  - name: enable docker
    systemd:
      state: started
      enabled: yes
      name: docker
    become: yes
