#######################################################################################################
# HPECP Installation
# created by Dirk Derichsweiler, do not hesitate to contact me. k8s@hpe.com
# modified by Erdinc Kaya
# Tested with HPECP 5.3
#######################################################################################################

###
- hosts: "{{ groups['controllers'] | first }}"
  gather_facts: yes
  vars:
    gateway_ips : "{{ groups['gateway'] | list }}"

  tasks:
  - name: configure hpecp
    copy:
      dest: ~/.hpecp.conf
      content: |-
        [default]
        api_host = {{ groups['controllers'] | first }}
        api_port = 8080
        use_ssl = True
        verify_ssl = False
        warn_ssl = False
        username = admin
        password = {{ admin_password }}
      force: yes

  - name: copy private key
    copy:
      src: "../../generated/controller.prv_key"
      dest: "/home/centos/controller.prv_key"
      owner: "centos"
      group: "centos"
      mode: 0600

  - name: check if ecp is installed
    stat:
      path: "/opt/bluedata"
    register: hpecp_installed

  - name: check ecp install file
    stat:
      path: "/home/centos/{{ install_file }}"
    register: installation_file

  - name: download ecp install file
    get_url:
      url: "{{ download_url }}"
      dest: "/home/centos/{{ install_file }}"
      mode: '0755'
    when: not installation_file.stat.exists
    
  - stat: path=/home/centos/ca-cert.pem
    register: cert_file
  - name: copy certificate
    copy:
      src: "../../generated/ca-cert.pem"
      dest: "/home/centos/ca-cert.pem"
      owner: "centos"
      group: "centos"
      mode: 0644
    when: not cert_file.stat.exists

  - name: copy certificate key
    copy:
      src: "../../generated/ca-key.pem"
      dest: "/home/centos/ca-key.pem"
      owner: "centos"
      group: "centos"
      mode: 0600
    when: not cert_file.stat.exists
  
  - name: install ecp
    shell: "/home/centos/{{ install_file }} --skipeula --default-password {{ admin_password }} --ssl-cert /home/centos/ca-cert.pem --ssl-priv-key /home/centos/ca-key.pem"
    when: not hpecp_installed.stat.exists
    # become: yes

  - name: configure ecp
    shell: /opt/bluedata/common-install/scripts/start_install.py -c "{{ item }}" -p "{{ admin_password }}" -t 60 -s docker -d hpecplocal --cin ecp-demo -k no --no-local-tenant-storage --routable no
    when: not hpecp_installed.stat.exists
    with_items: "{{ groups['controllers'] }}"

  - name: install python3
    yum:
      name: 
        - python3
        - python3-pip
        - expect
      state: latest
    register: yum
    become: yes

  - name: install hpecp client
    shell: pip3 install --user hpecp pexpect
    # become: yes

  - name: check ecp gateway
    shell: ~/.local/bin/hpecp gateway list --output text
    register: gw_result

  - name: site lockdown
    shell: ~/.local/bin/hpecp lock create "Install Gateway"
    when: gw_result.stdout == ""

  - name: install ecp gateway
    shell: ~/.local/bin/hpecp gateway create-with-ssh-key --ip "{{ item }}" --proxy-node-hostname "{{ gateway_pub_dns }}" --ssh-key-file ./controller.prv_key
    with_items: "{{ groups['gateway'] | list }}"
    when: gw_result.stdout == ""
  
  - name: exit site lockdown
    shell: ~/.local/bin/hpecp lock delete-all --timeout-secs 1800
    when: gw_result.stdout == ""

  - name: AD config
    copy:
      dest: ~/adconf.json
      content: |-
        { 
          "external_identity_server":  {
            "bind_pwd":"5ambaPwd@",
            "user_attribute":"sAMAccountName",
            "bind_type":"search_bind",
            "bind_dn":"cn=Administrator,CN=Users,DC=samdom,DC=example,DC=com",
            "host":"{{ groups['ad_server'] | list | first }}",
            "security_protocol":"ldaps",
            "base_dn":"CN=Users,DC=samdom,DC=example,DC=com",
            "verify_peer": false,
            "type":"Active Directory",
            "port":636 
          }
        }
      force: yes

  - name: configure global AD
    shell: ~/.local/bin/hpecp httpclient post /api/v2/config/auth --json-file ~/adconf.json
