- hosts: gworkers
  tasks:

  - name: disable nouveau
    blockinfile: 
      block: |-
        blacklist nouveau
        options nouveau modeset=0
      path: "/etc/modprobe.d/blacklist-nouveau.conf"
      owner: root
      group: root
      mode: 0644
      create: yes
    become: yes

  - name: 
    shell: "dracut /boot/initramfs-$(uname -r).img $(uname -r) --force"
    register: imagebuild
    become: yes

  - name: reboot gpunode
    reboot:
      reboot_timeout: 300
      connect_timeout: 5
      pre_reboot_delay: 0
      post_reboot_delay: 30
    when: imagebuild.changed
    become: True

  ### Install GPU drivers & configure the gworkers
  - name: check nvidia-smi
    shell: "command -v nvidia-smi"
    register: command_out
    ignore_errors: yes

  - name: install kernel packages
    package:
      name: 
        - kernel-headers
        - gcc-c++
        - perl
        - pciutils
      state: latest
    become: yes
    register: packages
    when: command_out.failed

  - name: install nvidia drivers
    shell: |-
      cd /tmp
      curl -O https://us.download.nvidia.com/tesla/470.57.02/NVIDIA-Linux-x86_64-470.57.02.run
      chmod +x ./NVIDIA-Linux-*.run
      ./NVIDIA-Linux-*.run -s
      nvidia-modprobe -u -c=0
      rm /tmp/NVIDIA-Linux-*.run
    become: yes
    when: command_out.failed

  - name: configure MIG
    shell: |-
      nvidia-smi -L | grep A100
      if [ "$?" == 0 ]; then
        nvidia-smi -mig 1
        nvidia-smi mig -cgi 19,19,19,19,19,19,19 -C
      fi
    become: yes
