- hosts: all:!mapr
  tasks:
  - name: configure yum for ipv4
    lineinfile:
      dest: /etc/yum.conf
      line: ip_resolve=4
    become: True 

  - name: Enable EPEL Repository on CentOS 7
    yum:
      name:
        - epel-release
        - bash-completion
      state: latest
    when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'
    become: yes

  - name: update packages
    package:
      name: '*'
      state: latest
    register: package
    ignore_errors: yes
    when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'
    become: yes

  - name: configure selinux
    selinux:
      state: permissive
      policy: targeted
    become: True
    register: selinux

- hosts: gateway
  gather_facts: False
  tasks:
  - name: reboot gateway
    reboot:
      reboot_timeout: 300
      connect_timeout: 5
      pre_reboot_delay: 0
      post_reboot_delay: 30
    when: selinux.reboot_required or package.changed
    become: True

- hosts: all:!gateway:!mapr
  gather_facts: False
  tasks:
  - name: reboot others
    reboot:
      reboot_timeout: 300
      connect_timeout: 5
      pre_reboot_delay: 0
      post_reboot_delay: 30
    when: selinux.reboot_required or package.changed
    become: True
