## Configure mapr centos hosts
- hosts: mapr
  gather_facts: no
  tasks:
  ### FROM: https://github.com/mapr-emea/mapr-ansible/tree/master/roles
  - name: update sysctl
    lineinfile:
      dest: /etc/sysctl.conf
      regexp: "{{ item.regex }}"
      line: "{{ item.line }}"
      create: true
    with_items:
      - regex: ^vm\.swappiness
        line: vm.swappiness = 1
      - regex: ^net\.ipv4\.tcp_retries2
        line: net.ipv4.tcp_retries2 = 5
      - regex: ^vm\.overcommit_memory
        line: vm.overcommit_memory = 0
      - regex: ^net\.ipv4\.tcp_fin_timeout
        line: net.ipv4.tcp_fin_timeout = 30
    become: yes
    register: sysctl

  - name: install python3
    package:
      name: 
        - python3
        - python3-pip
        - expect
      state: latest
    become: yes

  # - name: permissions for pam
  #   file:
  #     path: /etc/pam.d/system-auth-pc
  #     state: directory
  #     mode: 0644
  #   become: yes

  # - name: settings for mapr (3/5)
  #   shell: echo never | sudo tee /sys/kernel/mm/transparent_hugepage/enabled

  # - name: settings for mapr (4/5)
  #   shell: >
  #     echo "
  #     soft memlock unlimited
  #     hard memlock unlimited
  #     mapr - nofile 65536
  #     mapr - nproc 64000
  #     mapr - memlock unlimited
  #     mapr - core unlimited
  #     mapr - nice -10
  #     " | sudo tee -a /etc/security/limits.conf

  # - name: settings for mapr (5/5)
  #   shell: tuned-adm profile network-latency
  #   become: yes

  - name: reboot df nodes
    reboot: 
      reboot_timeout: 300
      connect_timeout: 5
      pre_reboot_delay: 0
      post_reboot_delay: 30
    become: yes
    when: sysctl.changed
