## Configure mapr centos hosts
- hosts: "{{ groups['mapr'] }}"
  tasks:
  ### FROM: https://github.com/mapr-emea/mapr-ansible/tree/master/roles
  - selinux: state=disabled
    become: yes
    register: selinux
  - name: Set /etc/sysctl.conf
    lineinfile:
      dest: /etc/sysctl.conf
      regexp: "{{item.regex}}"
      line: "{{item.line}}"
      create: true
    with_items:
      - regex: ^vm\.swappiness
        line: vm.swappiness = 1
      - regex: ^net\.ipv4\.tcp_retries2
        line: net.ipv4.tcp_retries2 = 5
      - regex: ^vm\.overcommit_memory
        line: vm.overcommit_memory = 0
      - regex: ^net\.ipv4\.tcp_fin_timeout
        line: net.ipv4.tcp_fin_timeout = 30
    become: yes
  - name: Ensure permissions for PAM config /etc/pam.d/system-auth-pc (2/5)
    file:
      path: /etc/pam.d/system-auth-pc
      state: directory
      mode: 0644
    become: yes
  - name: Install SSSD
    vars:
      packages_RedHat: ['samba-winbind', 'sssd', 'samba-common', 'samba-client', 'authconfig', 'openldap-clients', 'oddjob', 'oddjob-mkhomedir', 'adcli']
    package: name={{ item }} state=present
    with_items: "{{ vars['packages_' + ansible_os_family] }}"
    become: yes
  - name: Configure sssd.conf
    copy: dest=/etc/sssd/sssd.conf content={{ sssd_file }}
    become: yes
    vars:
      sssd_file: |-
        [sssd]
        config_file_version = 2
        debug_level = 1
        domains = {{ ad_realm }}
        services = nss, pam, ssh
        [domain/{{ ad_realm }}]
        id_provider = ad
        auth_provider = ad
        access_provider = ad
        chpass_provider = ad
        ldap_id_mapping = true
        ldap_schema = rfc2307bis
        ad_server = {{ groups['ad_server'] | first }}
        krb5_realm = {{ ad_realm }}
        # no dynamic dns update
        dyndns_update = false
        dyndns_refresh_interval = 43200
        dyndns_update_ptr = false
        dyndns_ttl = 3600
        ad_enable_gc = true
        ldap_sasl_mech = GSSAPI
        ldap_krb5_keytab = /etc/krb5.keytab
        ldap_krb5_init_creds = true
        ad_gpo_access_control = disabled
        override_homedir = /home/%u
        override_shell = /bin/bash
        # Users and groups are not enumerated to reduce trafic
        enumerate = false
        ldap_access_order = expire
        ldap_account_expire_policy = ad
        ldap_force_upper_case_realm = true
        case_sensitive = false
        ldap_referrals = false
        # perf
        cache_credentials = true
  - name: Set /etc/sssd/sssd.conf to chmod 400
    file: path=/etc/sssd/sssd.conf mode=0400
    become: yes
  - name: Configure smb.conf
    copy: dest=/etc/samba/smb.conf content={{ smb_file }}
    vars:
      mapr_workgroup: "samdom"
      smb_file: |-
        [global]
        security = ads
        workgroup = {{ mapr_workgroup }}
        realm = {{ ad_realm }}
        kerberos method = secrets and keytab
        passdb backend = tdbsam
        unix extensions = yes
        client signing = yes
        client use spnego = yes
    become: yes
  - name: Join to Windows domain
    shell: echo '5ambaPwd@' | sudo net ads join -U administrator
  - name: Enable and start the SSSD  service
    service: name=sssd state=restarted enabled=yes
    become: yes
  - name: Change PAM configuration with Redhat authconfig
    shell: authconfig --enablesssd --enablesssdauth  --disablekrb5 --enablemkhomedir --update --enablecache
    become: yes

  - name: settings for mapr (3/5)
    shell: echo never | sudo tee /sys/kernel/mm/transparent_hugepage/enabled

  - name: settings for mapr (4/5)
    shell: >
      echo "
      soft memlock unlimited
      hard memlock unlimited
      mapr - nofile 65536
      mapr - nproc 64000
      mapr - memlock unlimited
      mapr - core unlimited
      mapr - nice -10
      " | sudo tee -a /etc/security/limits.conf

  - name: settings for mapr (5/5)
    shell: tuned-adm profile network-latency
    become: yes

  - name: reboot df nodes
    reboot: 
      reboot_timeout: 300
      connect_timeout: 5
      pre_reboot_delay: 0
      post_reboot_delay: 30
    become: yes
    when: selinux.changed
