- hosts: gworkers
  tasks:
  ### Install GPU drivers & configure the gworkers
  - name: check nvidia-smi
    shell: "command -v nvidia-smi"
    register: command_out
    ignore_errors: yes

  - name: install kernel packages
    package:
      name: 
        - kernel-headers
        - gcc-c++
        - perl
        - pciutils
      state: latest
    become: yes
    register: packages
    when: command_out.failed

  - name: install nvidia drivers
    shell: |-
      cd /tmp
      curl -O https://us.download.nvidia.com/tesla/470.82.01/NVIDIA-Linux-x86_64-470.82.01.run
      chmod +x ./NVIDIA-Linux-*.run
      ./NVIDIA-Linux-*.run -s
      nvidia-modprobe -u -c=0
      rm /tmp/NVIDIA-Linux-*.run
    become: yes
    when: command_out.failed
