apiVersion: v1
data:
  MLFLOW_ARTIFACT_ROOT: czM6Ly9tbGZsb3c= #s3://mlflow
  AWS_ACCESS_KEY_ID: MLFLOW_ADMIN_USER # YWRtaW4= #admin
  AWS_SECRET_ACCESS_KEY: MLFLOW_ADMIN_PASSWORD
kind: Secret
metadata:
  name: mlflow-sc
  labels:
    kubedirector.hpe.com/secretType: mlflow
type: Opaque
---
apiVersion: "kubedirector.hpe.com/v1beta1"
kind: "KubeDirectorCluster"
metadata:
  name: "MLFLOW_CLUSTER"
  namespace: "TENANTNS"
  labels:
    description: "CreatedByEzdemo"
spec:
  app: "mlflow"
  namingScheme: "CrNameRole"
  appCatalog: "local"
  connections:
    secrets:
      - mlflow-sc
  roles:
    -
      id: "controller"
      members: 1
      resources:
        requests:
          cpu: "2"
          memory: "4Gi"
          nvidia.com/gpu: "0"
        limits:
          cpu: "2"
          memory: "4Gi"
          nvidia.com/gpu: "0"
      storage:
        size: "20Gi"
        storageClassName: "STORAGECLASS"

      #Note: "if the application is based on hadoop3 e.g. using StreamCapabilities interface, then change the below dtap label to 'hadoop3', otherwise for most applications use the default 'hadoop2'"
      podLabels:
        hpecp.hpe.com/dtap: "hadoop2"
