apiVersion: "kubedirector.hpe.com/v1beta1"
kind: "KubeDirectorCluster"
metadata:
  name: "TRAINING_CLUSTER"
  namespace: "TENANTNS"
  labels:
    description: "CreatedByEzdemo"
spec:
  app: "training-engine"
  namingScheme: "CrNameRole"
  appCatalog: "local"
  connections:
    secrets:
      - KC_SECRET
      - hpecp-ext-auth-secret
  roles:
    -
      id: "LoadBalancer"
      members: 1
      resources:
        requests:
          cpu: "2"
          memory: "4Gi"
          nvidia.com/gpu: "0"
        limits:
          cpu: "2"
          memory: "4Gi"
          nvidia.com/gpu: "0"
      #Note: "if the application is based on hadoop3 e.g. using StreamCapabilities interface, then change the below dtap label to 'hadoop3', otherwise for most applications use the default 'hadoop2'"
      podLabels:
        hpecp.hpe.com/dtap: "hadoop2"
    -
      id: "RESTServer"
      members: 1
      resources:
        requests:
          cpu: "2"
          memory: "4Gi"
          nvidia.com/gpu: "0"
        limits:
          cpu: "2"
          memory: "4Gi"
          nvidia.com/gpu: "0"
      #Note: "if the application is based on hadoop3 e.g. using StreamCapabilities interface, then change the below dtap label to 'hadoop3', otherwise for most applications use the default 'hadoop2'"
      podLabels:
        hpecp.hpe.com/dtap: "hadoop2"