name: ci

on:
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"

      - uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./src/.eslintrc.json
          contents: |
            {
                "plugins": [
                    "react"
                ],
                "extends": [
                    "eslint:recommended",
                    "plugin:react/recommended"
                ],
                "rules": {
                  'no-unused-vars': 'off',
                  '@typescript-eslint/no-unused-vars': 'error',
                }
            }
          write-mode: append
          
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build # will run `yarn build` command
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: erdincka/ezdemo:${{ steps.date.outputs.date }},erdincka/ezdemo:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
